[build]
  command="CI= npm run build"
  environment = { GENERATE_SOURCEMAP = "true" }
[context.next]
  environment = {
    REACT_APP_SERVICE_WORKER="true",
    REACT_APP_ENV="staging",
    REACT_APP_LOG_LEVEL="debug",
    REACT_APP_SERVER_URL="https://good-server.herokuapp.com/",
    REACT_APP_GUN_PUBLIC_URL="https://goodgun-dev.herokuapp.com/gun",
    REACT_APP_NETWORK="fuse",
    REACT_APP_ZOOM_LICENSE_KEY="",
    REACT_APP_ZOOM_SERVER_BASEURL="https://api.zoomauth.com/api/v2/biometrics",
    REACT_APP_SKIP_EMAIL_VERIFICATION="false",
    REACT_APP_AMPLITUDE_API_KEY="",
    REACT_APP_MARKET="false",
    REACT_APP_ETORO="false",
    REACT_APP_USE_TORUS="true",
    REACT_APP_GOOGLE_CLIENT_ID="",
    REACT_APP_FACEBOOK_APP_ID="",
    REACT_APP_AUTH0_CLIENT_ID="",
    REACT_APP_AUTH0_SMS_CLIENT_ID="",
    REACT_APP_AUTH0_DOMAIN="https://gooddollar.eu.auth0.com",
    REACT_APP_ENABLE_INVITES="true",
    REACT_APP_SHOW_INVITE="true",
    REACT_APP_CLAIM_QUEUE_ENABLED="true",
    REACT_APP_DASHBOARD_SHOW_INVITE="true",
    REACT_APP_DASHBOARD_URL="https://gooddashboard-next.herokuapp.com/",
    REACT_APP_ENV_PHASE_ZERO="false",
    REACT_APP_FACE_VERIFICATION_PRIVACY_URL="https://medium.com/gooddollar/gooddollar-identity-pillar-balancing-identity-and-privacy-part-i-face-matching-d6864bcebf54",
    REACT_APP_SENTRY_DSN="",
    REACT_APP_WEB3_SITE_URL="https://inivtation.herokuapp.com",
    REACT_APP_WEB3_TRANSPORT_PROVIDER="WebSocketProvider"
  }

[[headers]]
  for = "/torus/redirect"
  [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/zoom/resources/*"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
