[build]
command = "CI= rm -f .env* && CI= yarn build"
# TODO: uncomment after got permissions
#command = "CI= rm -f .env* && CI= yarn crowdin:sync && CI= yarn build"

[[headers]]
  for = "*"
  [headers.values]
    Cache-Control = "public, s-max-age=604800"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/service-worker.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[headers]]
  for = "/torus/sw.js"
  [headers.values]
    cache-control = "max-age=0,no-cache,no-store,must-revalidate"

[[headers]]
  for = "/torus/redirect"
  [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/torus/scripts.html"
    [headers.values]
      Content-Type = "text/html"

[[headers]]
  for = "/.well-known/apple-app-site-association"
    [headers.values]
      Content-Type = "application/json"

[[headers]]
  for = "/.well-known/assetlinks.json"
    [headers.values]
      Content-Type = "application/json"

[[headers]]
  for = "/zoom/resources/*_cache.wasm"
    [headers.values]
      cache-control = '''
        max-age=0,
        no-cache,
        no-store,
        must-revalidate'''

[build.environment]
NODE_VERSION = "14.17.6"
GENERATE_SOURCEMAP = "true"
NODE_ENV = "development"
YARN_FLAGS = "--production=false"
REACT_APP_SERVICE_WORKER = "true"
REACT_APP_ENV = "development"
REACT_APP_LOG_LEVEL = "debug"
REACT_APP_SERVER_URL = "https://good-server.herokuapp.com/"
REACT_APP_GUN_PUBLIC_URL = "https://goodgun-dev.herokuapp.com/gun"
REACT_APP_NETWORK = "fuse"
REACT_APP_SKIP_EMAIL_VERIFICATION = "false"
REACT_APP_MARKET_URL = "https://gooddollarmarketplace.sharetribe.com/en"
REACT_APP_ETORO = "false"
REACT_APP_AUTH0_DOMAIN = "https://gooddollar.eu.auth0.com"
REACT_APP_ENABLE_INVITES = "true"
REACT_APP_CLAIM_QUEUE_ENABLED = "false"
REACT_APP_DASHBOARD_URL = "https://gooddashboard-dev.herokuapp.com/"
REACT_APP_ENV_PHASE_ZERO = "false"
REACT_APP_ENV_PHASE_ONE = "true"
REACT_APP_FACE_VERIFICATION_PRIVACY_URL = "https://medium.com/gooddollar/gooddollar-identity-pillar-balancing-identity-and-privacy-part-i-face-matching-d6864bcebf54"
REACT_APP_WEB3_SITE_URL = "https://w3.gooddollar.org"
REACT_APP_USE_TORUS = "true"
REACT_APP_ENABLE_SELF_CUSTODY = "true"
REACT_APP_IPFS_GATEWAYS = "https://gateway.pinata.cloud/ipfs/{cid},https://{cid}.cf-ipfs.com,https://ipfs.io/ipfs/{cid},https://{cid}.ipfs.dweb.link"
REACT_APP_IPFS_LAZY_UPLOAD = "false"
REACT_APP_REALM_APP_ID = "wallet_dev-dhiht"
REACT_APP_PUBLIC_URL = "https://gooddev.netlify.app"
REACT_APP_CERAMIC_NODE_URL = "https://ceramic.gooddollar.org"

[context.master.environment]
REACT_APP_CERAMIC_NODE_URL = "https://ceramic-clay.3boxlabs.com"
REACT_APP_CERAMIC_INDEX = "k2t6wyfsu4pg1e0koxq485jc8hxnq8nwfqqn7zmu9y3afbez2zt999yogohtdk"
REACT_APP_CERAMIC_LIVE_INDEX = "k2t6wyfsu4pg2wnebmqd2fx4t7wes73qx0nu14kuof1wcg8jumhcawlgdu7tvn"

[context.staging.environment]
NODE_ENV = "staging"
REACT_APP_ENABLE_SELF_CUSTODY = "false"
REACT_APP_SERVICE_WORKER = "true"
REACT_APP_ENV = "staging"
REACT_APP_LOG_LEVEL = "debug"
REACT_APP_SERVER_URL = "https://goodserver-qa.herokuapp.com/"
REACT_APP_GUN_PUBLIC_URL = "https://goodgun-qa.herokuapp.com/gun"
REACT_APP_NETWORK = "staging"
REACT_APP_MARKET = "false"
REACT_APP_ETORO = "false"
REACT_APP_DASHBOARD_URL = "https://gooddashboard-qa.herokuapp.com/"
REACT_APP_ENV_PHASE_ZERO = "false"
REACT_APP_ENV_PHASE_ONE = "true"
REACT_APP_FACE_VERIFICATION_PRIVACY_URL = "https://medium.com/gooddollar/gooddollar-identity-pillar-balancing-identity-and-privacy-part-i-face-matching-d6864bcebf54"
REACT_APP_WEB3_SITE_URL = "https://w3.gooddollar.org"
REACT_APP_USE_TORUS = "true"
REACT_APP_REALM_APP_ID = "wallet_qa-iumgc"
REACT_APP_PUBLIC_URL = "https://goodqa.netlify.app"
REACT_APP_CERAMIC_INDEX = "k2t6wyfsu4pg1era7ujif58yjntagrm7xh2qfejoedpmf3ucxj8a9pf9l5dwb9"
REACT_APP_CERAMIC_LIVE_INDEX = "k2t6wyfsu4pg1qlhl3w62nfztkz15yaruza6aczll10e6dy1apm9vxfsjlz1t1"

[context.next.environment]
NODE_ENV = "production"
REACT_APP_SERVICE_WORKER = "true"
REACT_APP_ENV = "production"
REACT_APP_LOG_LEVEL = "off"
REACT_APP_SERVER_URL = "https://goodserver.gooddollar.org/"
REACT_APP_GUN_PUBLIC_URL = "https://goodgun-nvme.gooddollar.org/gun"
REACT_APP_NETWORK = "production"
REACT_APP_SKIP_MOBILE_VERIFICATION = "true"
REACT_APP_MARKET_URL = "https://gooddollarmarketplace.sharetribe.com/en"
REACT_APP_ETORO = "false"
REACT_APP_AUTH0_DOMAIN = "https://auth0.gooddollar.org"
REACT_APP_DASHBOARD_URL = "https://dashboard.gooddollar.org/"
REACT_APP_ENV_PHASE_ZERO = "false"
REACT_APP_ENV_PHASE_ONE = "true"
REACT_APP_FACE_VERIFICATION_PRIVACY_URL = "https://medium.com/gooddollar/gooddollar-identity-pillar-balancing-identity-and-privacy-part-i-face-matching-d6864bcebf54"
REACT_APP_WEB3_SITE_URL = "https://w3next.gooddollar.org"
REACT_APP_USE_TORUS = "true"
REACT_APP_TORUS_NETWORK = "mainnet"
REACT_APP_TORUS_PROXY_CONTRACT = "0x638646503746d5456209e33a2ff5e3226d698bea"
REACT_APP_TORUS_GOOGLE = "gooddollar-google"
REACT_APP_TORUS_FACEBOOK = "gooddollar-facebook"
REACT_APP_TORUS_GOOGLEAUTH0 = "gooddollar-google-auth0"
REACT_APP_ZOOM_PRODUCTION_MODE = "true"
REACT_APP_ENABLE_SELF_CUSTODY = "false"
REACT_APP_AB_TEST_PERCENTAGE = "0.5"
REACT_APP_REALM_APP_ID = "wallet_prod-obclo"
REACT_APP_PUBLIC_URL = "https://wallet.gooddollar.org"
REACT_APP_CERAMIC_INDEX = "k2t6wyfsu4pg2jmcm6a5i8pfvq8tkakd9k2bj2lyr0uibkxkt36stfgplaysi8"
REACT_APP_CERAMIC_LIVE_INDEX = "k2t6wyfsu4pg2w8m2vxj21twt5qri2ma314k5fkw27i784iklbhd83bv5pjb5m"
