name: Staging Release

on:
    push:
        branches:
            - develop
            - feature/GoodProtocolUI-32 # to be removed after testing
    # allow manual run
    workflow_dispatch:

jobs:
    deploy:
        name: Deploy Release
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Load node v14
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install dependencies
              uses: bahmutov/npm-install@v1

            - name: Build app
              run: yarn build

            # Pinning
            - name: Pin via web3 storage (Upload to web3 storage)
              id: web3
              uses: web3-storage/add-to-web3@v1
              with:
                  # web3_token: ${{ secrets.WEB3_STORAGE }} # to be swapped with actual token
                  web3_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweEU2RDQ4YjBiNjcyYTE3OUMzM2EwYjI3OTI1ZEI3NUNkMDc5OTNhRDEiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2MzQ2OTU0Mzg0NTcsIm5hbWUiOiJ0ZXN0IGdkIn0.DYLTIBAo500MqBEDp9pDYCJoOeOriTLsUwSvYu65XWM'
                  path_to_add: './build'

            - name: Display pin address
              run: |
                  echo published as ${{ steps.web3.outputs.url }}
                  echo cid ${{ steps.web3.outputs.cid }}

            - name: Update DNS with new IPFS hash
              env:
                  RECORD_ID: 'b92767ac95078f1ed897b639585cb5b6'
                  RECORD_NAME: 'fi-qa'
              run: |
                  curl \
                  -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_TOKEN }}" \
                  -H "Content-Type: application/json" \
                  -X PUT \
                  --data "{\"type\":\"TXT\",\"name\":\"${{ env.RECORD_NAME }}.${{ secrets.CLOUDFLARE_DOMAIN }}\",\"content\":\"dnslink=/ipfs/${{ steps.web3.outputs.cid }}\"}" \
                  -s "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records/${{ env.RECORD_ID }}"
